### ISSUE TITLE
Can't login: HTTP 422 and errors in blackcandy_app

### ISSUE THREAD

**Issue by maik-s** [aidewoode/black_candy#75]
Hi,
i have set up black candy exactly as mentioned in the readme.md, using your provided docker-compose.
The only difference is it runs behind a reverse proxy, which of course hands the traffic to bc.

Problem: I can't login with the provided default credentials.
Having a look in the browsers network tab shows that the request to /session is answered with an http status code 422.

Having a look in the docker logs of the blackcandy_app containter shows:

```
Error during failsafe response: Missing template errors/not_found, application/not_found with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:
  * "/app/app/views"

  /usr/local/bundle/gems/actionview-6.0.2.1/lib/action_view/path_set.rb:48:in `find'
  /usr/local/bundle/gems/actionview-6.0.2.1/lib/action_view/lookup_context.rb:129:in `find'
  /usr/local/bundle/gems/actionview-6.0.2.1/lib/action_view/renderer/template_renderer.rb:47:in `determine_template'
  /usr/local/bundle/gems/actionview-6.0.2.1/lib/action_view/renderer/template_renderer.rb:9:in `render'
  /usr/local/bundle/gems/actionview-6.0.2.1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
  /usr/local/bundle/gems/actionview-6.0.2.1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
  /usr/local/bundle/gems/actionview-6.0.2.1/lib/action_view/rendering.rb:118:in `block in _render_template'
  /usr/local/bundle/gems/actionview-6.0.2.1/lib/action_view/base.rb:304:in `in_rendering_context'
  /usr/local/bundle/gems/actionview-6.0.2.1/lib/action_view/rendering.rb:117:in `_render_template'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_controller/metal/streaming.rb:219:in `_render_template'
  /usr/local/bundle/gems/actionview-6.0.2.1/lib/action_view/rendering.rb:103:in `render_to_body'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/abstract_controller/rendering.rb:25:in `render'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_controller/metal/rendering.rb:36:in `render'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  /usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
  /usr/local/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
  /usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/core_ext/benchmark.rb:14:in `ms'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_controller/metal/instrumentation.rb:85:in `cleanup_view_runtime'
  /usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
  /app/app/controllers/errors_controller.rb:13:in `not_found'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/abstract_controller/base.rb:196:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  /usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
  /usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/notifications.rb:180:in `block in instrument'
  /usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  /usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/notifications.rb:180:in `instrument'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  /usr/local/bundle/gems/activerecord-6.0.2.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/abstract_controller/base.rb:136:in `process'
  /usr/local/bundle/gems/actionview-6.0.2.1/lib/action_view/rendering.rb:39:in `process'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_controller/metal.rb:191:in `dispatch'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_controller/metal.rb:252:in `dispatch'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_dispatch/journey/router.rb:49:in `block in serve'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_dispatch/journey/router.rb:32:in `each'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_dispatch/journey/router.rb:32:in `serve'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_dispatch/routing/route_set.rb:837:in `call'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/show_exceptions.rb:51:in `render_exception'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  /usr/local/bundle/gems/railties-6.0.2.1/lib/rails/rack/logger.rb:38:in `call_app'
  /usr/local/bundle/gems/railties-6.0.2.1/lib/rails/rack/logger.rb:26:in `block in call'
  /usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
  /usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
  /usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:80:in `tagged'
  /usr/local/bundle/gems/railties-6.0.2.1/lib/rails/rack/logger.rb:26:in `call'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
  /usr/local/bundle/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
  /usr/local/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
  /usr/local/bundle/gems/activesupport-6.0.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
  /usr/local/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
  /usr/local/bundle/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/host_authorization.rb:77:in `call'
  /usr/local/bundle/gems/railties-6.0.2.1/lib/rails/engine.rb:526:in `call'
  /usr/local/bundle/gems/puma-4.3.1/lib/puma/configuration.rb:228:in `call'
  /usr/local/bundle/gems/puma-4.3.1/lib/puma/server.rb:681:in `handle_request'
  /usr/local/bundle/gems/puma-4.3.1/lib/puma/server.rb:472:in `process_client'
  /usr/local/bundle/gems/puma-4.3.1/lib/puma/server.rb:328:in `block in run'
  /usr/local/bundle/gems/puma-4.3.1/lib/puma/thread_pool.rb:134:in `block in spawn_thread'

What am i doing wrong?
```

**Comment by maik-s** [comment]
After deleting the docker volumes and run docker-compose again the errors disappeared.

Furthermore, I was able to fix the 422 cant login error by adding ( #17 )

  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Forwarded-Ssl on;

to my nginx server block

https://github.com/aidewoode/black_candy/issues/17#issuecomment-766102509
